title: Polaris by VCA
url: https://www.wsg.gov.sg
favicon: /images/WSG_Favicon.png
colors:
  primary-color: "#330072"
  secondary-color: "#c5299b"
  media-colors:
    - title: media-color-one
      color: "#00b0b9"
    - title: media-color-two
      color: "#6cc24a"
    - title: media-color-three
      color: "#e87722"
    - title: media-color-four
      color: "#a05eb5"
    - title: media-color-five
      color: "#dbdddd"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d1vvmfjnbvfsad.amplifyapp.com
prod: https://master.d8zhuc1uh1o2o.amplifyapp.com
facebook-pixel: ""
shareicon: /images/20241129_WSG_Polaris_Logo_by_Workforce_Singapore_s_Volunteer_Career_Advisors_FA_path.jpg
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
